package ru.DailyProblemBot.enums;

public enum UserPhase {

    START,
    AUTH,
    SIGNIN_LOGIN, SIGNIN_PASSWORD,
    SIGNUP_NAME, SIGNUP_STUDENT_ID, SIGNUP_EMAIL, SIGNUP_PASSWORD,
    MAIN,
    TASK_CREATE_DESCRIPTION,
    TASK_CREATE_TITLE,
    TASK_CREATE_COST,
    TASK_CREATE_FILES,
    TASK_CREATE_ADDRESS,
    TASK_CREATE_CONFIRM,
    TASK_VOTE_SHOW,
    TASK_SHOW_ALL,
    TASK_SHOW_MY,
    TASK_EDIT_MENU,
    TASK_EDITING_MENU,
    TASK_EDIT_STATUS,
    TASK_EDIT_VOTES_LIMIT,
    TASK_EDIT_COST,
    TASK_EDIT_ADDRESS,
    TASK_EDIT_DESCRIPTION,
    TASK_EDIT_TITLE,
    TASK_EDIT_CONFIRM


}
